dist: jammy
language: php
php:
  - 8.2
before_script:
  - apt-get install libonig5 libonig-dev
  - composer install
script: vendor/bin/phpunit --colors=always -c ./configuration/phpunit.xml --testsuite All
